version: "3"

services:
  prometheus-server:
    container_name: prometheus-server
    image: prom/prometheus
    volumes:
      - ./prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana-server:
    container_name: grafana-server
    image: grafana/grafana-oss
    ports:
      - "4000:3000"